apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "next-poc.fullname" . | default .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: nextjs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: APP_ENV
              value: "{{ .Values.env.APP_ENV }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}